import{a as L,S as b,i as n}from"./assets/vendor-DQvd0HNi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))d(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const S="54847700-f9ce1488f27107b1b46500c94",v="https://pixabay.com/api/";async function f(e,r){return(await L.get(v,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader-wrapper"),p=document.querySelector(".load-more-btn"),P=new b(".gallery a");function g(e){const r=e.map(t=>`<li class="gallery-item">
    <a href="${t.largeImageURL}">
    <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" title=""></a>
    <ul class="info">
    <li class="info-item">likes: ${t.likes}</li>
    <li class="info-item">views: ${t.views}</li>
    <li class="info-item">comments: ${t.comments}</li>
    <li class="info-item">downloads: ${t.downloads}</li>
    </ul>
    
</li>`).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function q(){m.innerHTML=""}function y(){h.classList.add("active")}function a(){h.classList.remove("active")}function R(){p.classList.add("visible")}function u(){p.classList.remove("visible")}const B=document.querySelector(".form"),E=document.querySelector(".load-more-btn");let l="",i=1;const M=15;B.addEventListener("submit",$);E.addEventListener("click",O);async function $(e){e.preventDefault();const r=document.querySelector('[name="search-text"]').value.trim();if(r===""){n.show({message:"You need to type sonething for searching.",color:"red",position:"topRight"});return}l=r,i=1,q(),u(),y();try{const t=await f(l,i);if(a(),t.hits.length===0){n.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}g(t.hits),w(t.totalHits)}catch{a(),n.show({message:"Something went wrong. Please try again!",color:"red",position:"topRight"})}}async function O(){i+=1,u(),y();try{const e=await f(l,i);a(),g(e.hits),A(),w(e.totalHits)}catch{a(),n.show({message:"Something went wrong. Please try again!",color:"red",position:"topRight"})}}function w(e){i*M>=e?(u(),n.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"})):R()}function A(){const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
